[workspace]

members = [
    "kernel",
    "euralios_std",
    "pci",
    "rtl8139",
    "arp",
    "tcp",
    "gopher",
    "timing_test",
    "vga_driver",
    "ramdisk",
    "shell",
    "init"
]

