[workspace]

members = [
    "kernel",
    "keyboard",
    "euralios_std",
    "pci",
    "rtl8139",
    "virtio_net",
    "arp",
    "tcp",
    "gopher",
    "timing_test",
    "vga_driver",
    "ramdisk",
    "shell",
    "edit",
    "login",
    "init",
]

